### PR TITLE
Update delayed bridge contract

### PR DESCRIPTION
**Pull request by vch9**
The contract has changed in the Bifrost upgrade.

### CODE REVIEW

**Review by timothymcmackin — COMMENTED** [review]
Does it need to be changed here, too?
https://github.com/etherlinkcom/docs/blob/main/docs/network/building-kernel.md?plain=1#L40

**Comment by vch9** [comment]
I don't think so. I checked before opening the merge request but if I'm not wrong what you're linking is "how to build the kernel we initially deployed on mainnet". If so, it can never be changed, we just had an update in the upgrade

**Comment by timothymcmackin** [comment]
> I don't think so. I checked before opening the merge request but if I'm not wrong what you're linking is "how to build the kernel we initially deployed on mainnet". If so, it can never be changed, we just had an update in the upgrade

Got it. I just did a search for the old address to see if anything would come up. I'll approve now, go ahead and merge when you're ready.

**Review by timothymcmackin — APPROVED** [review]

**Comment by vch9** [comment]
@timothymcmackin I don't think I have the rights to merge but I believe it's ready

**Pull request merged**
