### PR TITLE
Docs for WXTZ token

### PR DESCRIPTION
**Pull request by timothymcmackin**
Renamed "token addresses" to "tokens" and added info on WXTZ from https://github.com/etherlinkcom/token-deployments/blob/main/docs/WXTZ.md.

Preview: https://docs-etherlink-git-wxtz-built-on-token-maint-trili-tech.vercel.app/building-on-etherlink/tokens#wxtz

### CODE REVIEW

**Comment by Camillebzd** [comment]
We have 2 choices:
1. we keep the all the Deployment and setup + test part
2. we remove all this part

The problem is "To add support for WXTZ to another chain, you must deploy its contract to that chain". You can't do that, we are the only ones able to deploy on a new chain and link it otherwise it would cause a critical breach for the users. So knowing they can't do that what is the points of these 2 parts? Maybe we can literally remove them and link to the official repo for the technical guys who want to play with it.

**Comment by Camillebzd** [comment]
We will also have to create a small tab with the different chains and addresses it is deployed on. We will also add a part right now saying that you can't send them cross chain.

**Comment by devon-n** [comment]
These are the addresses

WrappedTokenBridge: 0x1f8E735f424B7A49A885571A2fA104E8C13C26c7
WETH: 0xfc24f770F94edBca6D6f885E12d4317320BcB401
WBNB: 0xaA40A1cc1561c584B675cbD12F1423A32E2a0d8C
WAVAX: 0xe820995cD39B6E09EAa7e4e16337184b4A61B644
USDC: 0x796Ea11Fa2dD751eD01b53C372fFDB4AAa8f00F9
USDT: 0x2C03058C8AFC06713be23e58D2febC8337dbfE6A
SHIB: 0xBBD1F50A212357067318a84179892684e1Ac5181
WBTC: 0xbFc94CD2B1E55999Cfc7347a9313e88702B83d0F

**Comment by timothymcmackin** [comment]
> These are the addresses

Per your offline instructions I'll hold these until testing is complete.

**Comment by timothymcmackin** [comment]
> We will also have to create a small tab with the different chains and addresses it is deployed on. We will also add a part right now saying that you can't send them cross chain.

Clarified that you can't move WXTZ between chains here:
https://github.com/etherlinkcom/docs/pull/108/commits/d728091221170638082148e3a5f96efed460e160

**Review by Camillebzd — APPROVED** [review]

**Pull request merged**
