### PR TITLE
Link to Etherlink Safe

### PR DESCRIPTION
**Pull request by timothymcmackin**

### CODE REVIEW

**Comment by tauraitrilitech** [comment]
Hi Tim 

Just had a look we need to recreate docs on EVM multi-sigs, here is an example https://www.techtarget.com/searchcio/definition/multisig-multisignature#:~:text=Multisig%2C%20also%20called%20multisignature%2C%20is,required%20to%20approve%20a%20transaction. 

Took a look at the Tezos docs on this an they are incompatible with the understanding needed for an EVM multi-sig. At an elementary level we need to explain the concept as pertains to EVM

**Comment by timothymcmackin** [comment]
> Hi Tim
> 
> Just had a look we need to recreate docs on EVM multi-sigs, here is an example https://www.techtarget.com/searchcio/definition/multisig-multisignature#:~:text=Multisig%2C%20also%20called%20multisignature%2C%20is,required%20to%20approve%20a%20transaction.
> 
> Took a look at the Tezos docs on this an they are incompatible with the understanding needed for an EVM multi-sig. At an elementary level we need to explain the concept as pertains to EVM

I read that article and it seems that EVM multisigs are fundamentally the same as EVM multisigs, but to avoid confusing people I removed the link to info on Tezos multisigs and added info on what Safe does with EVM multisigs. How does this look? @tauraitrilitech

**Comment by tauraitrilitech** [comment]
Reviewed, looks good please proceed

**Review by tauraitrilitech — APPROVED** [review]
Yeap looks good

**Pull request merged**
