### PR TITLE
New architecture diagram and updates

### PR DESCRIPTION
**Pull request by timothymcmackin**
Working on a better architecture diagram that tells more about the roles of the different nodes in the most common modes while still treating the sequencer as a black box for now. Pairing this with some clarifications about the modes of the nodes in the diagram.

Preview: https://docs-etherlink-git-update-arch-diagram-trili-tech.vercel.app/network/architecture#transaction-lifecycle

New diagrams:

Overview diagram:
architecture-high-level

Full transaction diagram:

architecture-full

### CODE REVIEW

**Comment by devon-n** [comment]
It's easier for me to understand if we kept both diagrams. One labelled high level overview and another labelled detailed. What do you think?

**Comment by timothymcmackin** [comment]
> It's easier for me to understand if we kept both diagrams. One labelled high level overview and another labelled detailed. What do you think?

I tried it that way and maybe will add a third diagram for the delayed inbox path for transactions. What do you think?

**Review by devon-n — APPROVED** [review]

**Comment by sribst** [comment]
In the Layer 1 block I would remove the `transaction` because it could confuse the user between the layer 1 transaction and layer 2 ones.

**Comment by sribst** [comment]
Only 2 comment, diagram are good otherwise

**Comment by timothymcmackin** [comment]
This is tricky because we want to be accurate that only a hash of the Etherlink state is on layer 1, but because this section is about the lifecycle of a transaction, we also need to communicate that the transaction ends up on layer 1 (as part of the Etherlink state).

Changes:

- I want "transactions" to appear on the layer 1 block so I renamed them to "Layer 1 transactions and other operations"
- Changed "Smart Rollup states (including Etherlink)" to "Hashes of Smart Rollup states (including Etherlink)"
- Clarified some things around blueprints and states in the topic text.
- Clarified that the batcher node posts the blueprint to the SR inbox

**Pull request merged**
