### PR TITLE
Indexing contracts with TheGraph

### PR DESCRIPTION
**Pull request by timothymcmackin**
Based on these instructions:
https://github.com/alinobrasil/the_graph_getting_started/blob/main/The%20Graph%20Quick%20Start.md

### CODE REVIEW

**Comment by tauraitrilitech** [comment]
It should be explorer.etherlink.com instead of etherscan.io in point 2.

**Review by tauraitrilitech — CHANGES_REQUESTED** [review]
point 2. switch to explorer.etherlink.com

**Comment by timothymcmackin** [comment]
> It should be explorer.etherlink.com instead of etherscan.io in point 2.

@tauraitrilitech I thought the log said it was checking Etherscan but I can try again. Do you know how I can submit source to the Etherlink explorer?

**Comment by timothymcmackin** [comment]
Added instructions on verifying the source with the Etherlink block explorer.

**Review by tauraitrilitech — APPROVED** [review]
Thank you this looks about right

**Pull request merged**
