### PR TITLE
Link to bridge for Ghostnet

### PR DESCRIPTION
**Pull request by timothymcmackin**

### CODE REVIEW

**Comment by Camillebzd** [comment]
The text is confusing right now. Don't we want to clearly list them? Something like:
If you want to bridge your XTZ between Tezos and Etherlink, you can use the bridges:
- On testnet, use the testnet bridge (link to the bridge)
- On mainnet, use the mainnet bridge (link to the bridge)

**Comment by timothymcmackin** [comment]
> The text is confusing right now. Don't we want to clearly list them? Something like: If you want to bridge your XTZ between Tezos and Etherlink, you can use the bridges:
> 
> * On testnet, use the testnet bridge (link to the bridge)
> * On mainnet, use the mainnet bridge (link to the bridge)

Yep, that's clearer. How's this?

Screenshot 2024-06-04 at 11 53 15 AM

**Review by Camillebzd — APPROVED** [review]

**Comment by rohan-tez** [comment]
Screenshot 2024-06-05 at 11 37 23
@Camillebzd @timothymcmackin 

What do you think?

**Comment by Camillebzd** [comment]
Even better

**Comment by Camillebzd** [comment]
We absolutly need the ghostnet explanation.

**Pull request merged**
